---
# THIS PLAYBOOK MUST BE RUN FROM CLI
# PLEASE RUN WITH ANSIBLE-PLAYBOOK COMMAND
# ansible-playbook setup.yml
- name: TOWER CONFIGURATION IN PLAYBOOK FORM
  hosts: ansible
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: CREATE INVENTORY
      tower_inventory:
        name: "Durham"
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: CREATE INVENTORY
      tower_inventory:
        name: "Apex"
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: ADD LOTS OF HOSTS INTO TOWER
      tower_host:
        name: "windows{{item}}"
        inventory: "Durham"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      loop: "{{ range(1, 1500 + 1)|list }}"

    - name: ADD LOTS OF HOSTS INTO TOWER
      tower_host:
        name: "RHEL{{item}}"
        inventory: "Apex"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      loop: "{{ range(1, 1553 + 1)|list }}"
