---
# THIS PLAYBOOK MUST BE RUN FROM CLI
# PLEASE RUN WITH ANSIBLE-PLAYBOOK COMMAND
# ansible-playbook setup.yml
- name: TOWER CONFIGURATION IN PLAYBOOK FORM
  hosts: ansible
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: WE NEED TO RUN ANSIBLE >2.8 BECAUSE OF THE survey_spec
      assert:
        that:
          - ansible_version.major >= 2
          - ansible_version.minor >= 8
      register: result
      ignore_errors: true

    - name: ADDITIONAL INFORMATION IF ANSIBLE <2.8
      fail:
        msg: |
          PLEASE INSTALL ANSIBLE 2.8 OR NEWER
          INSTRUCTIONS ARE AT: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

          TO INSTALL DEV BRANCH VIA PIP:
          pip install git+https://github.com/ansible/ansible.git@devel
      when: result.failed

    - name: CREATE INVENTORY
      tower_inventory:
        name: "Workshop Inventory"
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: CREATE DEVICE INVENTORY
      tower_inventory:
        name: "{{item}}"
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      loop:
        - rtr1
        - rtr2
        - rtr3
        - rtr4

    - name: REMOVE INVENTORY
      tower_inventory:
        name: "Demo Inventory"
        organization: Default
        state: absent
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: ADD ANSIBLE HOST INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        variables:
          ansible_host: "{{ansible_host}}"
          ansible_user: "{{ansible_user}}"
          private_ip: "{{private_ip}}"

    - name: ADD CREDENTIAL INTO TOWER
      tower_credential:
        name: Workshop Credential
        ssh_key_data: "/home/{{ansible_user}}/.ssh/aws-private.pem"
        kind: ssh
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: ADD REPO INTO TOWER
      tower_project:
        name: "Workshop Project"
        organization: "Default"
        scm_type: git
        scm_url: "https://github.com/network-automation/tower_workshop"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: REMOVE DEMO JOB TEMPLATE
      tower_job_template:
        name: "Demo Job Template"
        job_type: "run"
        project: "Demo Project"
        state: absent
        playbook: "null"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: CREATE BACKUP JOB TEMPLATE
      tower_job_template:
        name: "BACKUP NETWORK CONFIG"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_backup.yml"
        credential: "Workshop Credential"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
      register: create_first_job
      until: create_first_job is not failed
      retries: 5

    - name: CREATE L3 INTERFACE JOB TEMPLATE
      tower_job_template:
        name: "CONFIGURE LAYER 3 INTERFACE"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_l3_interface.yml"
        credential: "Workshop Credential"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{playbook_dir}}/../templates/l3_interface.json') }}"
        ask_inventory: True
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: CREATE BANNER JOB TEMPLATE
      tower_job_template:
        name: "CONFIGURE BANNER"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_banner.yml"
        credential: "Workshop Credential"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{playbook_dir}}/../templates/banner.json') }}"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: CREATE SYSTEM JOB TEMPLATE
      tower_job_template:
        name: "CONFIGURE SYSTEM PROPERTIES (hostname, domain name, domain search, DNS)"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_system.yml"
        credential: "Workshop Credential"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{playbook_dir}}/../templates/system.json') }}"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

    - name: CREATE USER JOB TEMPLATE
      tower_job_template:
        name: "CONFIGURE USER"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_user.yml"
        credential: "Workshop Credential"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{playbook_dir}}/../templates/user.json') }}"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost

- name: NETWORK SETUP
  hosts: routers
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: ADD NETWORK HOSTS INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        variables:
          ansible_network_os: "{{ansible_network_os}}"
          ansible_host: "{{ansible_host}}"
          ansible_user: "{{ansible_user}}"
          private_ip: "{{private_ip}}"
          ansible_connection: "{{ansible_connection}}"
          ansible_become: yes
          ansible_become_method: enable

    - name: ADD NETWORK HOSTS INTO INDIVIDUAL INVENTORIES
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "{{ inventory_hostname }}"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        variables:
          ansible_network_os: "{{ansible_network_os}}"
          ansible_host: "{{ansible_host}}"
          ansible_user: "{{ansible_user}}"
          private_ip: "{{private_ip}}"
          ansible_connection: "{{ansible_connection}}"
