---
- name: GATHER INFORMATION FROM ROUTERS
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: SHOW COMMAND
      cli_command:
        command: "{{ tower_input | default('')}}"
      when: ansible_network_os is defined
      register: output

    - debug:
        msg: "{{ output }}"
