---
- name: CONFIGURE USER ON NETWORK DEVICES
  hosts: all
  gather_facts: no

  tasks:
    - name: LOAD PLATFORM ROLE {{ansible_network_os}}
      include_role:
        name: "{{ansible_network_os}}"
        tasks_from: user.yml
      when: ansible_network_os is defined
