# - name: RESTORE THE CONFIG
#   junos_config:
#     update: replace
#     src: "/tmp/backup/{{rollback_date}}/{{inventory_hostname}}"
#   register: config_output

- name: RESTORE THE CONFIG
  debug:
    msg: "RESTORE COMPLETE FOR JUNOS {{inventory_hostname}}"
