- name: CONFIGURE LAYER3 INTERFACE
  net_l3_interface:
    name: "{{interface_name}}"
    ipv4: "{{interface_ipv4 | default(omit) }}"
    ipv6: "{{interface_ipv6 | default(omit) }}"


# set interfaces lo0 unit 0 family inet address
